### ISSUE TITLE
App keeps loading after taking a video via capture

### ISSUE THREAD

**Issue by mcyusuf** [Jiikuy/VelocityCalculator#10]
#### Expected behavior
After capturing a video with phone camera via the app, it should receive and show it once I ended the recording.

#### Actual behavior
The app keeps showing loading. It won't display the video, and back button gets unresponsive tomreturn the app to its normal state.

#### How to reproduce
* Download velocity calculator from fdroid
* Calibrate the app
* Click the capture button and make a record then save
* The app would be stuck at loading

**App**: Velocity Calculator version 1.3.1 on fdroid<br>
**Operating system**: Android Lollipop 5.1

#### Recording Of The Bug
![videotogif_2018.02.13_11.56.17.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518519503/jxanzesqzaura4tqrvmr.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@mcyusuf/app-keeps-loading-after-taking-a-video-via-capture">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Jiikuy** [comment]
Could you provide a logcat? That would be very helpful.

**Comment by mcyusuf** [comment]
Okay. Would send soon

**Comment by mcyusuf** [comment]
[vcalc.txt](https://github.com/Jiikuy/VelocityCalculator/files/1732389/vcalc.txt)

**Comment by Jiikuy** [comment]
On my device it works. I'll close this.
